### ISSUE TITLE
PSR standards for paymentwall package

### ISSUE THREAD

**Issue by xDragonZ** [paymentwall/paymentwall-php#12]
Hello,

Currently the composer package is not compatible with laravel. It will be great if you guys could add PSR-0 or PSR-4 into composer.json

Ref:
https://laracasts.com/discuss/channels/general-discussion/using-non-laravel-composer-package-with-laravel
http://stackoverflow.com/a/15225170/925480

**Comment by LiangNex** [comment]
Close due as out of date
