### ISSUE TITLE
If Paymentwall_Base is deprecated, what should we use instead?

### ISSUE THREAD

**Issue by CyrilMazur** [paymentwall/paymentwall-php#15]
This commit https://github.com/paymentwall/paymentwall-php/blob/master/lib/Paymentwall/Base.php#L4 marked Paymentwall_Base as deprecated, so what should we use instead?

The doc is not up to date in this regard https://www.paymentwall.com/en/documentation/Digital-Goods-API/710#paymentwall_widget_call_flexible_wc_sign_calculation_and_building_widget_url

**Comment by davex69** [comment]
Hello,

Instead `Paymentwall_Base` we suggest use [`Paymentwall_Config`](https://github.com/paymentwall/paymentwall-php/blob/master/lib/Paymentwall/Config.php).

Example for Digital Goods:
```php
$configs = array (
    'public_key' => 'YOUR_PUBLIC_KEY',
    'private_key' => 'YOUR_SECRET_KEY'
);

Paymentwall_Config::getInstance()->set($configs);
```
Thanks.

**Comment by CyrilMazur** [comment]
Thanks.

**Comment by ivan-kovalyov** [comment]
We've also added description for initializing Paymentwall using both v1 and v2 of PHP Library:
https://github.com/paymentwall/paymentwall-php/blob/master/README.md
