### ISSUE TITLE
Library 1.2 version in composer

### ISSUE THREAD

**Issue by gyrocopter** [paymentwall/paymentwall-php#28]
I made it: 

`composer require paymentwall/paymentwall-php`

and took this result:

![1](https://cloud.githubusercontent.com/assets/12891379/10019754/d027ff14-6147-11e5-9ecc-d2a6f12b92df.png)

Library in 1.2 version, but actual is 2.1 version.

Please, say me, what can i do for getting latest version of your library, using composer ?

**Comment by davex69** [comment]
Hello,

`composer require paymentwall/paymentwall-php dev-master` will help you.

Thanks.
