### ISSUE TITLE
How to handle charges under risk review. ( How to listen to pingback )

### ISSUE THREAD

**Issue by kati-frantz** [paymentwall/paymentwall-php#36]
I'm implementing a simple payment with this payback, but I don't know how to handle charges under risk review. How do I know if charge is later declined or accepted ? In other words, how do i listen to the pingback from paymentwall ?

**Comment by LiangNex** [comment]
See [chargeback pingback](https://paymentwall.github.io/default-pingback#chargeback-pingback) for more details.
You will get a chargeback pingback when your user complain about his payment and want a refund.

We currently don't provide under risk review notification if you are not using [Brick](https://paymentwall.github.io/brick-home). The funds will be refunded directly if it is declined by our risk team.

**Comment by LiangNex** [comment]
Close due as out of date
