### ISSUE TITLE
Provide a shortcodes list as array or in json format

### ISSUE THREAD

**Issue by vaidas-lungis** [paymentwall/paymentwall-php#39]
it is pretty hard to fetch all available shortcodes from page
https://www.paymentwall.com/en/documentation/Payment-System-Shortcodes/2044

it would be nice to have a list in this library or as external package.

**Comment by LiangNex** [comment]
we provided [payment system api](https://www.paymentwall.com/en/documentation/Payment-Systems-API/2661) for this case.
