### ISSUE TITLE
Widget and PS property

### ISSUE THREAD

**Issue by vaidas-lungis** [paymentwall/paymentwall-php#40]
is it possible to know if selected payment method is available in clients country before widget is loaded? 
    Or if it is not supported, show default available methods selection in the widget instead of error message. 
> Sorry, this payment method is not available in your country

**Comment by LiangNex** [comment]
You can use our [payment system API](https://www.paymentwall.com/en/documentation/Payment-Systems-API/2661) to check wether it is supported for the countries of your customers.  

On the other hand, please check the payment system configuration of your project in Dashboard. Each payment methods has its own country coverage. The error message will still show up if no payment method is available for the ip address where request comes from.

**Comment by vaidas-lungis** [comment]
Thank you for the answer. 

> Each payment methods has its own country coverage. The error message will still show up if no payment method is available for the ip address where request comes from.

I want to prevent that message ;)
