### ISSUE TITLE
Can't add multiple products

### ISSUE THREAD

**Issue by adihanifsdr** [paymentwall/paymentwall-php#50]
`array(
new Paymentwall_Product('product301', 3.33, 'EUR', 'Product 1'), // first product in cart
new Paymentwall_Product('product607', 7.77, 'EUR', 'Product 2')  // second product in cart
),`

Why when i try to add 2 objects it didn't work but whenever i change it to only 1 it works
**2 products**
![image](https://user-images.githubusercontent.com/35891346/78326795-d74a8a80-75ad-11ea-8d2e-588157e94873.png)
**1 product only**
![image](https://user-images.githubusercontent.com/35891346/78326875-03660b80-75ae-11ea-89c4-105b1b7e588b.png)

**Comment by prashantbd** [comment]
Hi @adihanifsdr 

As per Paymentwall's current documentation, we do not support adding multiple products in the same request. 

For your inquiry, please share us the complete flow for the payments at our email integration@paymentwall.com and our team can provide you a reasonable solution. 

Best Regards,
Prashant.

**Comment by adihanifsdr** [comment]
> Hi @adihanifsdr
> 
> As per Paymentwall's current documentation, we do not support adding multiple products in the same request.
> 
> For your inquiry, please share us the complete flow for the payments at our email [integration@paymentwall.com](mailto:integration@paymentwall.com) and our team can provide you a reasonable solution.
> 
> Best Regards,
> Prashant.

Alright so i need put Total invoice due only to that Paymentwall_Product() instead of items isn't?

**Comment by prashantbd** [comment]
Yes, so you can instead pass amount & currency code to Checkout API and implement the cart functionality at your end.

You can refer to the documentation here: https://docs.paymentwall.com/integration/checkout/onetime
