### ISSUE TITLE
Please add support for php 8.2

### ISSUE THREAD

**Issue by itelmenko** [paymentwall/paymentwall-php#55]
Example of warning from php 8.2:

Creation of dynamic property Paymentwall_Product::$periodType is deprecated

**Comment by liufanhhh** [comment]
已收到您的来信，我会尽快回复，谢谢！

**Comment by itelmenko** [comment]
Any updates?

**Comment by paymentwall-dev** [comment]
Hi Igor,

Thank you for reaching out to us.

We have forwarded your concerns to our dev team, we will get back to you if
there are any updates.

Regards,
Paymentwall Team

**Comment by developersgit** [comment]
Any update on this yet??

**Comment by paymentwall-dev** [comment]
Hi Prince,

We have released an update to support php 8.2, you can find the latest
release version here
https://github.com/paymentwall/paymentwall-php/releases/tag/v2.2.4

Regards,
Paymentwall Team
